package com.lostVictories.model;

public class AvailableBattles {
	
	public static String[] availableBattles = new String[]{
			"Saar Offensive",
			"Operation Weserubung",
			"Norwegian Campaign",
			"Battles of Narvik",
			"Battle of the Netherlands",
			"Battle of Rotterdam",
			"Battle of Zeeland",
			"Battle of the Afsluitdijk",
			"Battle of the Grebbeberg",
			"Battle for The Hague",
			"Battle of Maastricht",
			"Battle of Belgium",
			"Battle of Fort Eben Emael",
			"Battle of Hannut",
			"Battle of Gembloux",
			"Battle of France",
			"Battle of Sedan",
			"Battle of Arras",
			"Siege of Calais",
			"Siege of Lille",
			"Operation Paula",
			"Battle of Dunkirk",
			"Battle of Saumur",
			"Battle of Britain",
			"The Hardest Day",
			"Battle of Britain Day",
			"Battle of Graveney Marsh",
			"The Blitz",
			"Operation Cerberus",
			"Operation Donnerkeil",
			"St Nazaire Raid",
			"Dieppe Raid",
			"Battle of Berlin",
			"Operation Overlord",
			"Battle of Normandy",
			"Invasion of Normandy",
			"Battle for Caen",
			"Operation Perch",
			"Battle of Carentan",
			"Battle of Cherbourg",
			"Battle of Villers Bocage",
			"Battle of Bloody Gulch",
			"Operation Epsom",
			"Operation Windsor",
			"Operation Charnwood",
			"Operation Jupiter",
			"Second Battle of the Odon",
			"Operation Goodwood",
			"Operation Atlantic",
			"Battle of Verrieres Ridge",
			"Operation Spring",
			"Operation Cobra",
			"Operation Totalize",
			"Operation Luttich",
			"Operation Tractable",
			"Battle of Hill 262",
			"Falaise pocket",
			"Battle for Brest",
			"Operation Dragoon",
			"Operation Romeo",
			"Battle of Port Cros",
			"Battle of La Ciotat",
			"Allied advance from Paris to the Rhine",
			"Clearing the Channel Coast",
			"Operation Astonia",
			"Siege of Dunkirk",
			"Operation Wellhit",
			"Operation Undergo",
			"Operation Market Garden",
			"Battle of Arnhem",
			"Lorraine Campaign",
			"Battle of Metz",
			"Battle of Nancy",
			"Battle of Moerbrugge",
			"Battle of Hurtgen Forest",
			"Battle of Hill 400",
			"Battle of Overloon",
			"Battle of Aachen",
			"Battle of Crucifix Hill",
			"Battle of the Scheldt",
			"Operation Queen",
			"Operation Clipper",
			"Battle of the Bulge",
			"Battle of Vianden",
			"Battle of St Vith",
			"Battle of Kesternich",
			"Battle of Foy",
			"Battle of Lanzerath Ridge",
			"Losheim Gap",
			"Battle of Clervaux",
			"Battle of Elsenborn Ridge",
			"Operation Stosser",
			"Siege of Bastogne",
			"Operation Bodenplatte",
			"Operation Nordwind",
			"Operation Blackcock",
			"Colmar Pocket",
			"Western Allied invasion of Germany",
			"Operation Veritable",
			"Operation Grenade",
			"Operation Lumberjack",
			"Operation Plunder",
			"Operation Varsity",
			"Operation Undertone",
			"Operation Amherst",
			"Battle of Kassel",
			"Battle of Heilbronn",
			"Ruhr Pocket",
			"Battle of Groningen"};
	

}
